### ISSUE TITLE
[BUG] Crash on create game command

### ISSUE THREAD

**Issue by djpiper28** [djpiper28/CockatriceTournamentBot#13]
Squirebot Log:
```py
authtoken=[REDACTED]
gamename=test-deck-hashes/Match1
password=[REDACTED]
playerCount=1
spectatorsAllowed=0
spectatorsNeedPassword=0
spectatorsCanChat=0
spectatorsCanSeeHands=0
onlyRegistered=0
playerDeckVerification=1
playerName=*
deckHash=ie03v62v

/usr/lib/python3.9/site-packages/urllib3/connectionpool.py:1013: InsecureRequestWarning: Unverified HTTPS request is being made to host 'tricebot.co.uk'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  warnings.warn(
<html>
<head><title>503 Service Temporarily Unavailable</title></head>
<body bgcolor="white">
<center><h1>503 Service Temporarily Unavailable</h1></center>
<hr><center>nginx/1.14.2</center>
</body>
</html>
```

Tricebot Backtrace:
```gdb
Program terminated with signal SIGABRT, Aborted.
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
50      ../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
[Current thread is 1 (Thread 0x7f5f2aee5700 (LWP 14323))]
(gdb) bt full
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
        set = {__val = {0, 0, 94841550184993, 0, 0, 140046468449392, 1, 0, 94841550269225, 82275357, 140046718879696, 
            94841550142581, 140046718880272, 140046738538184, 8589934615, 140046468388112}}
        pid = <optimized out>
        tid = <optimized out>
        ret = <optimized out>
#1  0x00007f5f2b934535 in __GI_abort () at abort.c:79
        save_stage = 1
        act = {__sigaction_handler = {sa_handler = 0x7f5f2aee4a10, sa_sigaction = 0x7f5f2aee4a10}, sa_mask = {__val = {
              140046718880208, 140046718880208, 140046718880208, 140046718880208, 140046718880208, 140046718880272, 0, 0, 0, 0, 
              0, 549755813888, 0, 0, 140046718880160, 140046718880416}}, sa_flags = 720259488, sa_restorer = 0x1000}
        sigs = {__val = {32, 0 <repeats 15 times>}}
#2  0x00007f5f2b98b508 in __libc_message (action=action@entry=do_abort, fmt=fmt@entry=0x7f5f2ba9628d "%s\n")
    at ../sysdeps/posix/libc_fatal.c:181
        ap = {{gp_offset = 24, fp_offset = 0, overflow_arg_area = 0x7f5f2aee4ab0, reg_save_area = 0x7f5f2aee4a40}}
        fd = 2
        list = <optimized out>
        nlist = <optimized out>
        cp = <optimized out>
        written = <optimized out>
#3  0x00007f5f2b991c1a in malloc_printerr (str=str@entry=0x7f5f2ba9443b "free(): invalid pointer") at malloc.c:5341
No locals.
#4  0x00007f5f2b99342c in _int_free (av=<optimized out>, p=<optimized out>, have_lock=<optimized out>) at malloc.c:4165
        size = 0
        fb = <optimized out>
        nextchunk = <optimized out>
        nextsize = <optimized out>
        nextinuse = <optimized out>
        prevsize = <optimized out>
--Type <RET> for more, q to quit, c to continue without paging--c
        bck = <optimized out>
        fwd = <optimized out>
        __PRETTY_FUNCTION__ = "_int_free"
#5  0x0000564204d95ef1 in getReplayFileName (gameID=7580908, gameNameUnfiltered=0x7f5f1c005a30 "test-deck-hashes/Match1", length=23, baseDIR=0x0) at /root/Tricebot/CockatriceTournamentBot/src/bot.c:518
        gameNameCP = 0x7f5f1c0034d0 "test-deck-hashes/Match1"
        makeDIR = 0
        tempFolderBaseLength = 1
        tempFolderName = 0x7f5f1c0034f0 "(null)/test-deck-"
        lastSlash = 16
        replayName = 0x1000 <error: Cannot access memory at address 0x1000>
#6  0x0000564204d94616 in eventHandler (c=0x7f5f1c001510, event=1, ev_data=0x7f5f2aee4e58, fn_data=0x7f5f1c002d60) at /root/Tricebot/CockatriceTournamentBot/src/api_server.c:1014
        data = 0x7f5f1c01bd70 "`\004\001\034_\177"
        replayName = 0x0
        paramdata = 0x7f5f1c00f4b0
        ID = 7580908
        s = 0x7f5f1c002d60
        api = 0x7fffc9d84240
#7  0x0000564204e75d95 in mg_call (c=0x7f5f1c001510, ev=1, ev_data=0x7f5f2aee4e58) at src/event.c:13
No locals.
#8  0x0000564204e7f0d9 in mg_mgr_poll (mgr=0x7f5f2aee4e90, ms=100) at src/sock.c:664
        c = 0x7f5f1c001510
        tmp = 0x7f5f1c000b20
        now = 1625421979225
        __func__ = "mg_mgr_poll"
#9  0x0000564204d94955 in pollingThread (apiIn=0x7fffc9d84240) at /root/Tricebot/CockatriceTournamentBot/src/api_server.c:1106
        mgr = {conns = 0x7f5f1c001510, dns4 = {url = 0x564204e9e8d1 "udp://8.8.8.8:53", c = 0x0}, dns6 = {url = 0x564204e9e8e8 "udp://[2001:4860:4860::8888]:53", c = 0x0}, dnstimeout = 3000, nextid = 11, userdata = 0x0}
        c = 0x7f5f1c000b20
        api = 0x7fffc9d84240
        cont = 1
#10 0x00007f5f2bdfdfa3 in start_thread (arg=<optimized out>) at pthread_create.c:486
        ret = <optimized out>
        pd = <optimized out>
        now = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140046718883584, 2751282794276124038, 140736579780142, 140736579780143, 140046718883584, 0, -2841541827801582202, -2841539778557839994}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = <optimized out>
#11 0x00007f5f2ba0b4cf in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
No locals.
```

**Comment by djpiper28** [comment]
Fixed in 2c14765858e89b8dfbdff4f35d0f5b5bbbdd416f
