### ISSUE TITLE
[BUG] Random crash, looks like something spooky with memory

### ISSUE THREAD

**Issue by djpiper28** [djpiper28/CockatriceTournamentBot#3]
```gdb
#0  0x0000559edbd6a220 in _ServerInfo_ReplayMatch_default_instance_ ()
[Current thread is 1 (Thread 0x7f28b47a0700 (LWP 18720))]
(gdb) bt full
#0  0x0000559edbd6a220 in _ServerInfo_ReplayMatch_default_instance_ ()
No symbol table info available.
#1  0x0000559edbc0e895 in freeGameListNodeNTS (gl=0x7f28e802eed0) at /root/Tricebot/CockatriceTournamentBot/src/game_struct.c:129
No locals.
#2  0x0000559edbc0e952 in freeGameList (g=0x7fff414dc7b0) at /root/Tricebot/CockatriceTournamentBot/src/game_struct.c:154
        tmp = 0x7f28e802eed0
        current = 0x7f28e8033cb0
#3  0x0000559edbc07e41 in botThread (in=0x7fff414dc6b8) at /root/Tricebot/CockatriceTournamentBot/src/bot.c:1379
        b = 0x7fff414dc6b8
        mgr = {conns = 0x0, dns4 = {url = 0x0, c = 0x0}, dns6 = {url = 0x0, c = 0x0}, dnstimeout = 0, nextid = 0, userdata = 0x0}
        c = 0x0
        onBotDisconnect = 0x0
#4  0x00007f28f247ffa3 in start_thread (arg=<optimized out>) at pthread_create.c:486
        ret = <optimized out>
        pd = <optimized out>
        now = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {139812803315456, -4480319371863313703, 139812811705774, 139812811705775, 139812803315456, 0, 
                4576745424954143449, 4576591579218391769}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, 
              cleanup = 0x0, canceltype = 0}}}
        not_first_call = <optimized out>
#5  0x00007f28f208d4cf in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95


================================


Thread 4 (Thread 0x7f28b4fa1700 (LWP 18141)):
#0  0x00007f28f21674e1 in ?? () from /lib/x86_64-linux-gnu/libgcc_s.so.1
#1  0x00007f28f20c7bb7 in __GI___dl_iterate_phdr (callback=0x7f28f21670b0, data=0x7f28b4fa0960) at dl-iteratephdr.c:75
#2  0x00007f28f2168361 in _Unwind_Find_FDE () from /lib/x86_64-linux-gnu/libgcc_s.so.1
#3  0x00007f28f2164a43 in ?? () from /lib/x86_64-linux-gnu/libgcc_s.so.1
#4  0x00007f28f2165f4f in ?? () from /lib/x86_64-linux-gnu/libgcc_s.so.1
#5  0x00007f28f216651c in _Unwind_ForcedUnwind () from /lib/x86_64-linux-gnu/libgcc_s.so.1
#6  0x00007f28f24890a0 in __GI___pthread_unwind (buf=<optimized out>) at unwind.c:121
#7  0x00007f28f24811f5 in __do_cancel () at pthreadP.h:305
#8  __pthread_exit (value=<optimized out>) at pthread_exit.c:28
#9  0x0000559edbc08118 in botThread (in=0x7fff414dc6b8) at /root/Tricebot/CockatriceTournamentBot/src/bot.c:1432
#10 0x00007f28f247ffa3 in start_thread (arg=<optimized out>) at pthread_create.c:486
#11 0x00007f28f208d4cf in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 3 (Thread 0x7f28f1567700 (LWP 23855)):
#0  0x00007f28f2085037 in __GI___select (nfds=4, readfds=0x7f28f1566d50, writefds=0x7f28f1566cd0, exceptfds=0x0, timeout=0x7f28f1566de0)
    at ../sysdeps/unix/sysv/linux/select.c:41
#1  0x0000559edbceba28 in mg_iotest (mgr=0x7f28f1566e90, ms=100) at src/sock.c:611
#2  0x0000559edbcebd64 in mg_mgr_poll (mgr=0x7f28f1566e90, ms=100) at src/sock.c:658
#3  0x0000559edbc015ed in pollingThread (apiIn=0x7fff414dc9c0) at /root/Tricebot/CockatriceTournamentBot/src/api_server.c:1064
#4  0x00007f28f247ffa3 in start_thread (arg=<optimized out>) at pthread_create.c:486
#5  0x00007f28f208d4cf in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 2 (Thread 0x7f28f1d6c740 (LWP 23853)):
#0  0x00007f28f205a720 in __GI___nanosleep (requested_time=requested_time@entry=0x7fff414dc610, remaining=remaining@entry=0x7fff414dc610)
    at ../sysdeps/unix/sysv/linux/nanosleep.c:28
#1  0x00007f28f205a62a in __sleep (seconds=0) at ../sysdeps/posix/sleep.c:55
#2  0x0000559edbc12a5d in main (argc=1, args=0x7fff414dcb88) at /root/Tricebot/CockatriceTournamentBot/src/main.c:501

Thread 1 (Thread 0x7f28b47a0700 (LWP 18720)):
#0  0x0000559edbd6a220 in _ServerInfo_ReplayMatch_default_instance_ ()
#1  0x0000559edbc0e895 in freeGameListNodeNTS (gl=0x7f28e802eed0) at /root/Tricebot/CockatriceTournamentBot/src/game_struct.c:129
#2  0x0000559edbc0e952 in freeGameList (g=0x7fff414dc7b0) at /root/Tricebot/CockatriceTournamentBot/src/game_struct.c:154
#3  0x0000559edbc07e41 in botThread (in=0x7fff414dc6b8) at /root/Tricebot/CockatriceTournamentBot/src/bot.c:1379
#4  0x00007f28f247ffa3 in start_thread (arg=<optimized out>) at pthread_create.c:486

```

**Comment by djpiper28** [comment]
Cause disconnection from server

**Comment by djpiper28** [comment]
I will add better connection drop error handling.

**Comment by djpiper28** [comment]
it appears this bug also fixed itself. why idk. how idk.
