### ISSUE TITLE
[BUG] Crash when games are created with "_" or " " in the name

### ISSUE THREAD

**Issue by djpiper28** [djpiper28/CockatriceTournamentBot#5]
**Describe the bug**
read title

**To Reproduce**
 - read title

**Expected behavior**

**Screenshots**

**Version (please complete the following information):**
 - Version 1.7

**Additional context**
```gdb
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007ffff7464535 in __GI_abort () at abort.c:79
#2  0x00007ffff74bb508 in __libc_message (action=action@entry=do_abort, fmt=fmt@entry=0x7ffff75c628d "%s\n") at ../sysdeps/posix/libc_fatal.c:181
#3  0x00007ffff74c1c1a in malloc_printerr (str=str@entry=0x7ffff75c443b "free(): invalid pointer") at malloc.c:5341
#4  0x00007ffff74c342c in _int_free (av=<optimized out>, p=<optimized out>, have_lock=<optimized out>) at malloc.c:4165
#5  0x00007ffff7c5e1bc in mbedtls_mpi_free () from /lib/x86_64-linux-gnu/libmbedcrypto.so.3
#6  0x00007ffff7c87505 in mbedtls_rsa_free () from /lib/x86_64-linux-gnu/libmbedcrypto.so.3
#7  0x00007ffff7c7e1c9 in ?? () from /lib/x86_64-linux-gnu/libmbedcrypto.so.3
#8  0x00007ffff7c7da88 in mbedtls_pk_free () from /lib/x86_64-linux-gnu/libmbedcrypto.so.3
#9  0x00007ffff7c3ad1c in mbedtls_x509_crt_free () from /lib/x86_64-linux-gnu/libmbedx509.so.0
#10 0x00005555556601fd in mg_tls_free (c=0x7fffe8002a50) at src/tls.c:228
#11 0x000055555565de52 in close_conn (c=0x7fffe8002a50) at src/sock.c:348
#12 0x000055555565f078 in mg_mgr_poll (mgr=0x7ffff6a14e90, ms=100) at src/sock.c:700
#13 0x00005555555745ed in pollingThread (apiIn=0x7fffffffe330) at /root/Tricebot/CockatriceTournamentBot/src/api_server.c:1064
#14 0x00007ffff792dfa3 in start_thread (arg=<optimized out>) at pthread_create.c:486
#15 0x00007ffff753b4cf in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```
that one time

then
```gdb
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007f0e23269535 in __GI_abort () at abort.c:79
#2  0x00007f0e232c0508 in __libc_message (action=action@entry=do_abort, fmt=fmt@entry=0x7f0e233cb28d "%s\n") at ../sysdeps/posix/libc_fatal.c:181
#3  0x00007f0e232c6c1a in malloc_printerr (str=str@entry=0x7f0e233c943b "free(): invalid pointer") at malloc.c:5341
#4  0x00007f0e232c842c in _int_free (av=<optimized out>, p=<optimized out>, have_lock=<optimized out>) at malloc.c:4165
#5  0x000056154425395e in google::protobuf::internal::ArenaStringPtr::DestroyNoArena (this=0x7f0e22816f88, 
    default_value=0x5615443a6c40 <google::protobuf::internal::fixed_address_empty_string[abi:cxx11]>)
    at /usr/include/google/protobuf/arenastring.h:322
#6  0x00005615442cb797 in Command_CreateGame::SharedDtor (this=0x7f0e22816f60)
    at /root/Tricebot/CockatriceTournamentBot/build/pb/room_commands.pb.cc:998
#7  0x00005615442cb71c in Command_CreateGame::~Command_CreateGame (this=0x7f0e22816f60, __in_chrg=<optimized out>)
    at /root/Tricebot/CockatriceTournamentBot/build/pb/room_commands.pb.cc:994
#8  0x0000561544245870 in sendCreateGameCommand (b=0x7ffd29c76128, gameName=0x7f0e140034f0 "Community Night/Match 1", 
    password=0x7f0e140034d0 "game-1", playerCount=4, joinAsSpectator=1, spectatorsAllowed=1, spectatorsCanChat=0, spectatorsNeedPassword=0, 
    spectatorsCanSeeHands=0, onlyRegistered=0, onlyBuddies=0, gameData=..., callbackFn=0x0) at /root/Tricebot/CockatriceTournamentBot/src/bot.c:1070
#9  0x000056154423f68f in serverCreateGameCommand (s=0x7f0e14019f80, c=0x7f0e140025f0, hm=0x7f0e22819820)
    at /root/Tricebot/CockatriceTournamentBot/src/api_server.c:613
#10 0x000056154423fad5 in eventHandler (c=0x7f0e140025f0, event=8, ev_data=0x7f0e22819820, fn_data=0x7f0e14019f80)
    at /root/Tricebot/CockatriceTournamentBot/src/api_server.c:718
#11 0x0000561544321a6b in mg_call (c=0x7f0e140025f0, ev=8, ev_data=0x7f0e22819820) at src/event.c:13
#12 0x0000561544324dab in http_cb (c=0x7f0e140025f0, ev=5, evd=0x7f0e22819e00, fnd=0x0) at src/http.c:1144
#13 0x0000561544321a41 in mg_call (c=0x7f0e140025f0, ev=5, ev_data=0x7f0e22819e00) at src/event.c:9
#14 0x0000561544329c5b in read_conn (c=0x7f0e140025f0, fn=0x5615443294b6 <ll_read(mg_connection*, void*, int, int*)>) at src/sock.c:298
#15 0x000056154432b009 in mg_mgr_poll (mgr=0x7f0e22819e90, ms=100) at src/sock.c:687
#16 0x00005615442405ed in pollingThread (apiIn=0x7ffd29c76430) at /root/Tricebot/CockatriceTournamentBot/src/api_server.c:1064
#17 0x00007f0e23732fa3 in start_thread (arg=<optimized out>) at pthread_create.c:486
#18 0x00007f0e233404cf in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

```
this another

**Comment by djpiper28** [comment]
I sh^t you not this bug fixed itself. why idk. how idk. but that is that.
